/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "your-component": {
    name: "your-component",
    description: "A placeholder component. Replace this with your custom shadcn component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/new-york-v4/ui/your-component.tsx",
      type: "registry:ui",
      target: "components/ui/your-component.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/your-component.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }